# Generated by Django 4.0.5 on 2022-06-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
