# Generated by Django 4.0.5 on 2022-06-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_produit_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('date_inscription', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
