# Generated by Django 4.0.5 on 2022-06-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='listecommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=20)),
                ('commande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drive.commande')),
                ('produit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drive.produit')),
            ],
        ),
    ]
