# Generated by Django 4.0.5 on 2022-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_listecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listecommande',
            name='commande',
        ),
        migrations.AddField(
            model_name='listecommande',
            name='commande',
            field=models.ManyToManyField(to='drive.commande'),
        ),
        migrations.RemoveField(
            model_name='listecommande',
            name='produit',
        ),
        migrations.AddField(
            model_name='listecommande',
            name='produit',
            field=models.ManyToManyField(to='drive.produit'),
        ),
    ]
